inherit: "config/calib.yaml"

# ============================================================================
# Calibrated Mode with Inpainting - Debug/Test Configuration
# This config enables all debugging features for testing inpainting integration
# ============================================================================

# Enable all dynamic processing features
use_dynamic_mask: True
refine_dynamic_mask_with_sam2: True
use_dynamic_mask_for_keyframes: True

# Inpainting configuration (for testing)
use_inpainting: True
inpainting_dilate_kernel: 15  # Standard dilation

# Enable ALL debug visualizations for testing
debug_save_dynamic_mask: True
debug_save_new_kf_dynamic_mask: True
debug_save_inpainting: True
debug_save_final_valid_opt_mask: True

# Tuned parameters for testing
dynamic_mask_threshold: 0.3  # Slightly more sensitive for testing
dynamic_point_low_confidence: 0.001

# Dataset settings for testing
dataset:
  subsample: 2  # Lower subsampling for faster testing 