inherit: "config/base.yaml"

use_calib: True
use_dynamic_mask: True
debug_save_dynamic_mask: True
refine_dynamic_mask_with_sam2: False

dynamic_mask_threshold: 0.35
dynamic_points_weight: 0.8
dataset:
  subsample: 4
